# Build and run all services

services: 
    matrix-divider:
        build: services\division-service
        #deploy:
         #   replicas: 100
          #  resources:
           #     limits:
            #        cpus: "0.1"
             #       memory: 50M

    matrix-multiplier:
        build: services\multiplication-service
        #deploy:
         #   replicas: 100
          #  resources:
           #     limits:
            #        cpus: "0.1"
             #       memory: 50M
    
    matrix-aggregator:
        build: services\aggregation-service
        
    
    
